services:
  server:
    build:
      context: .
    env_file:
      - dev.env
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
  agent:
    build:
      context: agent
    env_file:
      - ./agent/.env
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: pgvector/pgvector:0.7.0-pg15
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=coworker
      - POSTGRES_USER=coworker
      - POSTGRES_PASSWORD=coworker
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:

